config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    get "buyer/index"
    get "seller/index"
  end
  resources :users, only: [:new, :create]
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :auctions do
    patch "start", on: :member
    get "biddings", on: :collection
    get "active", on: :collection
    resources :bids, only: [:create]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/dashboard/buyer_controller.rb
class Dashboard::BuyerController < ApplicationController
  def index
    redirect_to root_path unless current_user.buyer?

    @auctions = Auction.active.order(
      Arel.sql("CASE auctions.status
        WHEN 'BIDDING' THEN 1
        WHEN 'ACTIVE' THEN 2
        WHEN 'INACTIVE' THEN 3
        WHEN 'CLOSED' THEN 4
        ELSE 5 END")
    )
  end
end

app/controllers/dashboard/seller_controller.rb
class Dashboard::SellerController < ApplicationController
  def index
    redirect_to root_path unless current_user.seller?

    @auctions = current_user.auctions.order(
      Arel.sql("CASE auctions.status
        WHEN 'BIDDING' THEN 1
        WHEN 'ACTIVE' THEN 2
        WHEN 'INACTIVE' THEN 3
        WHEN 'CLOSED' THEN 4
        ELSE 5 END")
    )
  end
end

app/views/dashboard/seller/index.html.haml
%h1{class: 'text-2xl font-bold'} Listing auctions
%div{class: 'mx-auto mt-16 grid max-w-2xl grid-cols-2 gap-6 sm:gap-8 lg:mt-10 lg:max-w-none lg:grid-cols-2'}
  = render partial: 'auctions/auction', collection: @auctions

- if @auctions.empty?
  %p You haven't created any auctions yet.
  = link_to "Create an auction", new_auction_path, class: "group inline-flex items-center justify-center rounded-full py-2 px-4 text-sm font-semibold focus:outline-hidden focus-visible:outline-2 focus-visible:outline-offset-2 bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500 active:bg-blue-800 active:text-blue-100 focus-visible:outline-blue-600"