config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    get "buyer/index"
    get "seller/index"
  end
  resources :users, only: [:new, :create]
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :auctions do
    patch "start", on: :member
    get "biddings", on: :collection
    get "active", on: :collection
    resources :bids, only: [:create]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  root "home#index"
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :buyer, class_name: 'User'

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :auction, :buyer, presence: true

  validates_each :amount do |record, attr, value|
    next if record.auction.nil?

    current_price = record.auction.current_price || record.auction.starting_price
    record.errors.add(attr, 'must be greater than the current price') if value <= current_price
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_auction

  # GET /bids or /bids.json
  def index
    @bids = Bid.all
  end

  # POST /bids or /bids.json
  def create
    @bid = current_user.bids.build(bid_params)
    @bid.auction = @auction

    @bid = MakeBidService.call(bid_params: bid_params, bidder: current_user, auction: @auction)
    if @bid.persisted?
      render action: 'create'
    else
      render action: 'error'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:auction_id])
    end

    # Only allow a list of trusted parameters through.
    def bid_params
      params.expect(bid: [ :amount ])
    end
end

app/views/bids/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@bid) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :amount
    = f.association :auction
    = f.association :buyer

  .form-actions
    = f.button :submit

app/views/bids/create.turbo_stream.erb
<%= turbo_stream.replace @auction do %>
  <%= render partial: "auctions/auction", locals: { auction: @auction } %>
<% end %>

app/views/bids/edit.html.haml
%h1 Editing bid

= render 'form'

= link_to 'Show', @bid
\|
= link_to 'Back', bids_path

app/views/bids/error.turbo_stream.erb
<turbo-stream action="update" target="auction-<%= @auction.id %>-bid-error">
  <template>
    <%= @bid.errors.full_messages.join(', ') %>
  </template>
</turbo-stream>

app/views/bids/index.html.haml
%h1 Listing bids

%table
  %thead
    %tr
      %th Amount
      %th Auction
      %th Buyer
      %th
      %th
      %th

  %tbody
    - @bids.each do |bid|
      %tr
        %td= bid.amount
        %td= bid.auction
        %td= bid.buyer
        %td= link_to 'Show', bid
        %td= link_to 'Edit', edit_bid_path(bid)
        %td= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Bid', new_bid_path

app/views/bids/new.html.haml
%h1 New bid

= render 'form'

= link_to 'Back', bids_path

app/views/bids/show.html.haml
%p#notice= notice

%p
  %b Amount:
  = @bid.amount
%p
  %b Auction:
  = @bid.auction
%p
  %b Buyer:
  = @bid.buyer

= link_to 'Edit', edit_bid_path(@bid)
\|
= link_to 'Back', bids_path