config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    get "buyer/index"
    get "seller/index"
  end
  resources :users, only: [:new, :create]
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :auctions do
    patch "start", on: :member
    get "biddings", on: :collection
    get "active", on: :collection
    resources :bids, only: [:create]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  root "home#index"
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  has_many :bids, dependent: :destroy

  validates :title, presence: true
  validates :starting_price, presence: true, numericality: { greater_than: 0 }
  validates :current_price, numericality: { greater_than: :starting_price }, allow_nil: true
  validates :duration, presence: true, numericality: { greater_than: 0 }
  validates :status, inclusion: { in: %w[INACTIVE ACTIVE BIDDING CLOSED] }

  scope :active, -> { where(status: %w(ACTIVE BIDDING)) }


  def inactive?
    status == 'INACTIVE'
  end

  def active?
    status == 'ACTIVE'
  end

  def bidding?
    status == 'BIDDING'
  end

  def closed?
    status == 'CLOSED'
  end

  def highest_bid
    bids.order(amount: :desc).first
  end

  def on_bid?(user)
    highest_bid&.buyer == user
  end

  def out_bid?(user)
    (highest_bid&.buyer || user) != user
  end

  def no_bid?(user)
    bids.where(buyer: user).empty?
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: %i[edit update destroy start ]

  def new
    @auction = current_user.auctions.build
  end

  def edit
  end

  def create
    @auction = current_user.auctions.build(auction_params.merge(status: 'INACTIVE'))

    if @auction.save
      redirect_to dashboard_seller_index_path, notice: "Auction was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @auction.update(auction_params)
      redirect_to dashboard_seller_index_path, notice: "Auction was successfully updated."
    else
      render :edit, status: :unprocessable
    end
  end

  def destroy
    @auction.destroy!

    redirect_to auctions_path, status: :see_other, notice: "Auction was successfully destroyed."
  end

  def show
    @auction = Auction.find(params[:id])
  end

  def start
    if StartAuctionService.call(auction: @auction)
      render action: 'start'
    else
      render turbo_stream: turbo_stream.replace(@auction, partial: "auctions/auction", locals: { auction: @auction })
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = current_user.auctions.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def auction_params
      params.expect(auction: [ :title, :description, :starting_price, :current_price, :start_date, :start_time_only, :duration, :status, :seller_id ])
    end
end

app/views/auctions/_auction.html.haml
- bg_status = { 'INACTIVE' => 'bg-white', 'ACTIVE' => 'bg-yellow-100', 'BIDDING' => 'bg-lime-500', 'CLOSED' => 'bg-gray-500'}
%div.auction{ id: dom_id(auction), 'data-controller': 'auction', 'data-controller-id': auction.id, 'data-auction-id': auction.id, class: "relative rounded-2xl p-6 shadow-xl shadow-slate-900/10 #{bg_status[auction.status]}" }
  %p
    %b Seller:
    = auction.seller.name
  %hr{class: 'border-t border-gray-500 my-4'}
  %p
    %b Title:
    = auction.title
  %p
    %b Description:
    = auction.description
  %p
    %b Status:
    %span.auction-status
      = auction.status
  - if auction.start_time.present?
    %p
      %b Start time:
      = auction.start_time.strftime('%Y-%m-%d %H:%M:%S')
  %p
    %b Duration:
    = auction.duration
  %p
    %b Starting price:
    = auction.starting_price

  - if auction.on_bid?(current_user)
    - bidding_class = 'bg-sky-300'
  - elsif auction.out_bid?(current_user)
    - bidding_class = 'bg-rose-500'
  - else bidding_class = 'bg-white'

  .p-2{class: bidding_class}
    %p
      %b Highest bid:
      .highest-bid= auction.highest_bid&.amount
    %p
      %b Current bidder:
      .highest-bidder= auction.highest_bid&.buyer&.name

  - if current_user == auction.seller
    %hr{class: 'border-t border-gray-500 my-4'}
    - unless auction.bids.present?
      = link_to 'Edit', edit_auction_path(auction), class: "group inline-flex items-center justify-center rounded-full py-2 px-4 text-sm font-semibold focus:outline-hidden focus-visible:outline-2 focus-visible:outline-offset-2 bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500 active:bg-blue-800 active:text-blue-100 focus-visible:outline-blue-600"
    %p &nbsp;
    - if auction.inactive?
      = link_to 'Start', start_auction_path(auction), data: {turbo_method: :patch, turbo_stream: true}, class: "group inline-flex items-center justify-center rounded-full py-2 px-4 text-sm font-semibold focus:outline-hidden focus-visible:outline-2 focus-visible:outline-offset-2 bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500 active:bg-blue-800 active:text-blue-100 focus-visible:outline-blue-600"
  - if current_user.buyer? && (auction.active? || auction.bidding?)
    %hr{class: 'border-t border-gray-500 my-4'}
    = simple_form_for([auction, auction.bids.build], html: {class: 'flex flex-wrap gap-2'}, data: { turbo: true }) do |f|
      %p.basic-full.w-full.text-rose-500{ id: "auction-#{auction.id}-bid-error" }
      = f.input :amount, label: false, input_html: {class: 'rounded-lg p-2 border border-gray-300'}
      = f.button :submit, 'Place bid', class: 'rounded-lg p-2 bg-blue-600 text-white hover:bg-blue-500'

app/views/auctions/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@auction) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, label_html: { class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" }, input_html: { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" }
    = f.input :description, label_html: { class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" }, input_html: { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" }
    = f.input :starting_price, label_html: { class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" }, input_html: { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" }
    = f.input :duration, as: :integer, label: 'Duration (in minutes)', label_html: { class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" }, input_html: { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" }

  .form-actions.mt-4
    = f.button :submit, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer"

app/views/auctions/active.html.haml
%h1 All active auctions

= render @auctions

app/views/auctions/edit.html.haml
%h1 Editing auction

= render 'form'

= link_to 'Show', @auction
\|
= link_to 'Back', auctions_path

app/views/auctions/index.html.haml
%h1 Listing auctions
%div{class: 'mx-auto mt-16 grid max-w-2xl grid-cols-2 gap-6 sm:gap-8 lg:mt-10 lg:max-w-none lg:grid-cols-2'}
  = render @auctions

app/views/auctions/new.html.haml
%h1 New auction

= render 'form'

app/views/auctions/show.html.haml
= render "auctions/auction", auction: @auction

app/views/auctions/show.turbo_stream.erb
<%= turbo_stream.prepend "active-auctions" do %>
  <%= render partial: "auctions/auction", locals: { auction: @auction } %>
<% end %>

app/views/auctions/start.turbo_stream.erb
<%= turbo_stream.replace @auction do %>
  <%= render partial: "auctions/auction", locals: { auction: @auction } %>
<% end %>